image: "docker:stable"
variables:
  REGISTRY: "eu.gcr.io"
  BUILD_TAG: "eu.gcr.io/torchbox-internal-tools/heroku-restarter:$CI_COMMIT_REF_NAME"
stages:
  - build
build:
  stage: build
  before_script:
    - mkdir -p $HOME/.docker
    - echo "$DOCKER_AUTH_CONFIG" >> "$HOME/.docker/config.json"
  script:
    - docker build -t $BUILD_TAG -f Dockerfile .
    - docker push $BUILD_TAG